### ISSUE TITLE
Latest IDEA version support

### ISSUE THREAD

**Issue by raul-guerrero** [iman89/liquigen#1]
Hi,

I can't seem to find the plugin on the IDEA plugin repository using IDEA's latest version 2018.2.4

Will you add support and get it back on the official plugin repo?

Thanks for the efforts!

**Comment by alex-inv** [comment]
I've committed a new release which is compiled against IDEA 2018.1 and should be available up to the latest version, please check it out

**Comment by alex-inv** [comment]
3f285bc

**Comment by raul-guerrero** [comment]
Awesome thanks Alexey! Keep up the great work
